# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btypes.proto\x12\x0e\x62\x61\x63kbone.types* \n\tLoraClass\x12\x05\n\x01\x41\x10\x00\x12\x05\n\x01\x42\x10\x01\x12\x05\n\x01\x43\x10\x02*#\n\x0e\x41\x63tivationType\x12\x08\n\x04OTAA\x10\x00\x12\x07\n\x03\x41\x42P\x10\x01*+\n\x08RxWindow\x12\r\n\tUNDEFINED\x10\x00\x12\x07\n\x03RX1\x10\x01\x12\x07\n\x03RX2\x10\x02\x42\"\n\x1etech.lar.sp.backbone.api.typesP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'types_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036tech.lar.sp.backbone.api.typesP\001'
  _LORACLASS._serialized_start=31
  _LORACLASS._serialized_end=63
  _ACTIVATIONTYPE._serialized_start=65
  _ACTIVATIONTYPE._serialized_end=100
  _RXWINDOW._serialized_start=102
  _RXWINDOW._serialized_end=145
# @@protoc_insertion_point(module_scope)
